// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/transcription.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscriptionService_CreateSession_FullMethodName            = "/transcription.TranscriptionService/CreateSession"
	TranscriptionService_StreamAudio_FullMethodName              = "/transcription.TranscriptionService/StreamAudio"
	TranscriptionService_EndSession_FullMethodName               = "/transcription.TranscriptionService/EndSession"
	TranscriptionService_GetSessionTranscriptions_FullMethodName = "/transcription.TranscriptionService/GetSessionTranscriptions"
	TranscriptionService_SearchTranscriptions_FullMethodName     = "/transcription.TranscriptionService/SearchTranscriptions"
)

// TranscriptionServiceClient is the client API for TranscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Serviço de transcrição de áudio
type TranscriptionServiceClient interface {
	// Cria uma nova sessão de transcrição
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// Stream de áudio para transcrição (bidirecional)
	// Cliente envia chunks de áudio, servidor responde com transcrições
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptionResult], error)
	// Finaliza uma sessão
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	// Busca transcrições de uma sessão
	GetSessionTranscriptions(ctx context.Context, in *GetSessionTranscriptionsRequest, opts ...grpc.CallOption) (*GetSessionTranscriptionsResponse, error)
	// Busca por texto (full-text search)
	SearchTranscriptions(ctx context.Context, in *SearchTranscriptionsRequest, opts ...grpc.CallOption) (*SearchTranscriptionsResponse, error)
}

type transcriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriptionServiceClient(cc grpc.ClientConnInterface) TranscriptionServiceClient {
	return &transcriptionServiceClient{cc}
}

func (c *transcriptionServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptionResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranscriptionService_ServiceDesc.Streams[0], TranscriptionService_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, TranscriptionResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscriptionService_StreamAudioClient = grpc.BidiStreamingClient[AudioChunk, TranscriptionResult]

func (c *transcriptionServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) GetSessionTranscriptions(ctx context.Context, in *GetSessionTranscriptionsRequest, opts ...grpc.CallOption) (*GetSessionTranscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionTranscriptionsResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_GetSessionTranscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) SearchTranscriptions(ctx context.Context, in *SearchTranscriptionsRequest, opts ...grpc.CallOption) (*SearchTranscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTranscriptionsResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_SearchTranscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscriptionServiceServer is the server API for TranscriptionService service.
// All implementations must embed UnimplementedTranscriptionServiceServer
// for forward compatibility.
//
// Serviço de transcrição de áudio
type TranscriptionServiceServer interface {
	// Cria uma nova sessão de transcrição
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// Stream de áudio para transcrição (bidirecional)
	// Cliente envia chunks de áudio, servidor responde com transcrições
	StreamAudio(grpc.BidiStreamingServer[AudioChunk, TranscriptionResult]) error
	// Finaliza uma sessão
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	// Busca transcrições de uma sessão
	GetSessionTranscriptions(context.Context, *GetSessionTranscriptionsRequest) (*GetSessionTranscriptionsResponse, error)
	// Busca por texto (full-text search)
	SearchTranscriptions(context.Context, *SearchTranscriptionsRequest) (*SearchTranscriptionsResponse, error)
	mustEmbedUnimplementedTranscriptionServiceServer()
}

// UnimplementedTranscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscriptionServiceServer struct{}

func (UnimplementedTranscriptionServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedTranscriptionServiceServer) StreamAudio(grpc.BidiStreamingServer[AudioChunk, TranscriptionResult]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedTranscriptionServiceServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedTranscriptionServiceServer) GetSessionTranscriptions(context.Context, *GetSessionTranscriptionsRequest) (*GetSessionTranscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionTranscriptions not implemented")
}
func (UnimplementedTranscriptionServiceServer) SearchTranscriptions(context.Context, *SearchTranscriptionsRequest) (*SearchTranscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTranscriptions not implemented")
}
func (UnimplementedTranscriptionServiceServer) mustEmbedUnimplementedTranscriptionServiceServer() {}
func (UnimplementedTranscriptionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTranscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscriptionServiceServer will
// result in compilation errors.
type UnsafeTranscriptionServiceServer interface {
	mustEmbedUnimplementedTranscriptionServiceServer()
}

func RegisterTranscriptionServiceServer(s grpc.ServiceRegistrar, srv TranscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscriptionService_ServiceDesc, srv)
}

func _TranscriptionService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranscriptionServiceServer).StreamAudio(&grpc.GenericServerStream[AudioChunk, TranscriptionResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscriptionService_StreamAudioServer = grpc.BidiStreamingServer[AudioChunk, TranscriptionResult]

func _TranscriptionService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_GetSessionTranscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTranscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).GetSessionTranscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_GetSessionTranscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).GetSessionTranscriptions(ctx, req.(*GetSessionTranscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_SearchTranscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTranscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).SearchTranscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_SearchTranscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).SearchTranscriptions(ctx, req.(*SearchTranscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscriptionService_ServiceDesc is the grpc.ServiceDesc for TranscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcription.TranscriptionService",
	HandlerType: (*TranscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _TranscriptionService_CreateSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _TranscriptionService_EndSession_Handler,
		},
		{
			MethodName: "GetSessionTranscriptions",
			Handler:    _TranscriptionService_GetSessionTranscriptions_Handler,
		},
		{
			MethodName: "SearchTranscriptions",
			Handler:    _TranscriptionService_SearchTranscriptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _TranscriptionService_StreamAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/transcription.proto",
}
