// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/transcription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Criar sessão
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadados opcionais
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_transcription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID da sessão
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Timestamp ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_proto_transcription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Stream de áudio
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // UUID da sessão
	ChunkSequence int32                  `protobuf:"varint,2,opt,name=chunk_sequence,json=chunkSequence,proto3" json:"chunk_sequence,omitempty"` // Número sequencial do chunk
	AudioData     []byte                 `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`              // Dados do áudio (raw bytes)
	AudioFormat   string                 `protobuf:"bytes,4,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"`        // Formato: "wav", "mp3", "opus", etc
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`          // Ex: 16000, 44100
	Channels      int32                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`                                // 1 = mono, 2 = stereo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_api_proto_transcription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetChunkSequence() int32 {
	if x != nil {
		return x.ChunkSequence
	}
	return 0
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetAudioFormat() string {
	if x != nil {
		return x.AudioFormat
	}
	return ""
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type TranscriptionResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkSequence   int32                  `protobuf:"varint,2,opt,name=chunk_sequence,json=chunkSequence,proto3" json:"chunk_sequence,omitempty"`
	Language        string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`       // Idioma detectado: "pt", "en", etc
	Text            string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`               // Texto transcrito
	Confidence      float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // Confiança: 0.0 a 1.0
	DurationSeconds float64                `protobuf:"fixed64,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsFinal         bool                   `protobuf:"varint,8,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // Se é resultado final ou parcial
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranscriptionResult) Reset() {
	*x = TranscriptionResult{}
	mi := &file_api_proto_transcription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionResult) ProtoMessage() {}

func (x *TranscriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionResult.ProtoReflect.Descriptor instead.
func (*TranscriptionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{3}
}

func (x *TranscriptionResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TranscriptionResult) GetChunkSequence() int32 {
	if x != nil {
		return x.ChunkSequence
	}
	return 0
}

func (x *TranscriptionResult) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscriptionResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptionResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscriptionResult) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TranscriptionResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TranscriptionResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// Finalizar sessão
type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "completed", "error", "paused"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_api_proto_transcription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EndSessionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalChunks          int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalDurationSeconds float64                `protobuf:"fixed64,4,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	PrimaryLanguage      string                 `protobuf:"bytes,5,opt,name=primary_language,json=primaryLanguage,proto3" json:"primary_language,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_api_proto_transcription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EndSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndSessionResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *EndSessionResponse) GetTotalDurationSeconds() float64 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *EndSessionResponse) GetPrimaryLanguage() string {
	if x != nil {
		return x.PrimaryLanguage
	}
	return ""
}

// Buscar transcrições
type GetSessionTranscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Padrão: 100
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Padrão: 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionTranscriptionsRequest) Reset() {
	*x = GetSessionTranscriptionsRequest{}
	mi := &file_api_proto_transcription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTranscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTranscriptionsRequest) ProtoMessage() {}

func (x *GetSessionTranscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTranscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionTranscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionTranscriptionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionTranscriptionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetSessionTranscriptionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetSessionTranscriptionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transcriptions []*Transcription       `protobuf:"bytes,1,rep,name=transcriptions,proto3" json:"transcriptions,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSessionTranscriptionsResponse) Reset() {
	*x = GetSessionTranscriptionsResponse{}
	mi := &file_api_proto_transcription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionTranscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionTranscriptionsResponse) ProtoMessage() {}

func (x *GetSessionTranscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionTranscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionTranscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionTranscriptionsResponse) GetTranscriptions() []*Transcription {
	if x != nil {
		return x.Transcriptions
	}
	return nil
}

func (x *GetSessionTranscriptionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Transcription struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkSequence   int32                  `protobuf:"varint,3,opt,name=chunk_sequence,json=chunkSequence,proto3" json:"chunk_sequence,omitempty"`
	Language        string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Text            string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence      float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AudioFormat     string                 `protobuf:"bytes,8,opt,name=audio_format,json=audioFormat,proto3" json:"audio_format,omitempty"`
	SampleRate      int32                  `protobuf:"varint,9,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels        int32                  `protobuf:"varint,10,opt,name=channels,proto3" json:"channels,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transcription) Reset() {
	*x = Transcription{}
	mi := &file_api_proto_transcription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcription) ProtoMessage() {}

func (x *Transcription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcription.ProtoReflect.Descriptor instead.
func (*Transcription) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{8}
}

func (x *Transcription) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transcription) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Transcription) GetChunkSequence() int32 {
	if x != nil {
		return x.ChunkSequence
	}
	return 0
}

func (x *Transcription) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Transcription) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcription) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Transcription) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Transcription) GetAudioFormat() string {
	if x != nil {
		return x.AudioFormat
	}
	return ""
}

func (x *Transcription) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Transcription) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *Transcription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Busca full-text
type SearchTranscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Padrão: 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTranscriptionsRequest) Reset() {
	*x = SearchTranscriptionsRequest{}
	mi := &file_api_proto_transcription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTranscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTranscriptionsRequest) ProtoMessage() {}

func (x *SearchTranscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTranscriptionsRequest.ProtoReflect.Descriptor instead.
func (*SearchTranscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTranscriptionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTranscriptionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchTranscriptionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transcriptions []*Transcription       `protobuf:"bytes,1,rep,name=transcriptions,proto3" json:"transcriptions,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchTranscriptionsResponse) Reset() {
	*x = SearchTranscriptionsResponse{}
	mi := &file_api_proto_transcription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTranscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTranscriptionsResponse) ProtoMessage() {}

func (x *SearchTranscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_transcription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTranscriptionsResponse.ProtoReflect.Descriptor instead.
func (*SearchTranscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_transcription_proto_rawDescGZIP(), []int{10}
}

func (x *SearchTranscriptionsResponse) GetTranscriptions() []*Transcription {
	if x != nil {
		return x.Transcriptions
	}
	return nil
}

func (x *SearchTranscriptionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_proto_transcription_proto protoreflect.FileDescriptor

const file_api_proto_transcription_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/transcription.proto\x12\rtranscription\"\xa2\x01\n" +
	"\x14CreateSessionRequest\x12M\n" +
	"\bmetadata\x18\x01 \x03(\v21.transcription.CreateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"\xd1\x01\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0echunk_sequence\x18\x02 \x01(\x05R\rchunkSequence\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\x12!\n" +
	"\faudio_format\x18\x04 \x01(\tR\vaudioFormat\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x05R\bchannels\"\x90\x02\n" +
	"\x13TranscriptionResult\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0echunk_sequence\x18\x02 \x01(\x05R\rchunkSequence\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x01R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bis_final\x18\b \x01(\bR\aisFinal\"J\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xcc\x01\n" +
	"\x12EndSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x124\n" +
	"\x16total_duration_seconds\x18\x04 \x01(\x01R\x14totalDurationSeconds\x12)\n" +
	"\x10primary_language\x18\x05 \x01(\tR\x0fprimaryLanguage\"n\n" +
	"\x1fGetSessionTranscriptionsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x89\x01\n" +
	" GetSessionTranscriptionsResponse\x12D\n" +
	"\x0etranscriptions\x18\x01 \x03(\v2\x1c.transcription.TranscriptionR\x0etranscriptions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xdf\x02\n" +
	"\rTranscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0echunk_sequence\x18\x03 \x01(\x05R\rchunkSequence\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x01R\x0fdurationSeconds\x12!\n" +
	"\faudio_format\x18\b \x01(\tR\vaudioFormat\x12\x1f\n" +
	"\vsample_rate\x18\t \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\n" +
	" \x01(\x05R\bchannels\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"I\n" +
	"\x1bSearchTranscriptionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x85\x01\n" +
	"\x1cSearchTranscriptionsResponse\x12D\n" +
	"\x0etranscriptions\x18\x01 \x03(\v2\x1c.transcription.TranscriptionR\x0etranscriptions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\x85\x04\n" +
	"\x14TranscriptionService\x12Z\n" +
	"\rCreateSession\x12#.transcription.CreateSessionRequest\x1a$.transcription.CreateSessionResponse\x12P\n" +
	"\vStreamAudio\x12\x19.transcription.AudioChunk\x1a\".transcription.TranscriptionResult(\x010\x01\x12Q\n" +
	"\n" +
	"EndSession\x12 .transcription.EndSessionRequest\x1a!.transcription.EndSessionResponse\x12{\n" +
	"\x18GetSessionTranscriptions\x12..transcription.GetSessionTranscriptionsRequest\x1a/.transcription.GetSessionTranscriptionsResponse\x12o\n" +
	"\x14SearchTranscriptions\x12*.transcription.SearchTranscriptionsRequest\x1a+.transcription.SearchTranscriptionsResponseB)Z'github.com/Ant0nioSouza/GoVox/api/protob\x06proto3"

var (
	file_api_proto_transcription_proto_rawDescOnce sync.Once
	file_api_proto_transcription_proto_rawDescData []byte
)

func file_api_proto_transcription_proto_rawDescGZIP() []byte {
	file_api_proto_transcription_proto_rawDescOnce.Do(func() {
		file_api_proto_transcription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_transcription_proto_rawDesc), len(file_api_proto_transcription_proto_rawDesc)))
	})
	return file_api_proto_transcription_proto_rawDescData
}

var file_api_proto_transcription_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_transcription_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),             // 0: transcription.CreateSessionRequest
	(*CreateSessionResponse)(nil),            // 1: transcription.CreateSessionResponse
	(*AudioChunk)(nil),                       // 2: transcription.AudioChunk
	(*TranscriptionResult)(nil),              // 3: transcription.TranscriptionResult
	(*EndSessionRequest)(nil),                // 4: transcription.EndSessionRequest
	(*EndSessionResponse)(nil),               // 5: transcription.EndSessionResponse
	(*GetSessionTranscriptionsRequest)(nil),  // 6: transcription.GetSessionTranscriptionsRequest
	(*GetSessionTranscriptionsResponse)(nil), // 7: transcription.GetSessionTranscriptionsResponse
	(*Transcription)(nil),                    // 8: transcription.Transcription
	(*SearchTranscriptionsRequest)(nil),      // 9: transcription.SearchTranscriptionsRequest
	(*SearchTranscriptionsResponse)(nil),     // 10: transcription.SearchTranscriptionsResponse
	nil,                                      // 11: transcription.CreateSessionRequest.MetadataEntry
}
var file_api_proto_transcription_proto_depIdxs = []int32{
	11, // 0: transcription.CreateSessionRequest.metadata:type_name -> transcription.CreateSessionRequest.MetadataEntry
	8,  // 1: transcription.GetSessionTranscriptionsResponse.transcriptions:type_name -> transcription.Transcription
	8,  // 2: transcription.SearchTranscriptionsResponse.transcriptions:type_name -> transcription.Transcription
	0,  // 3: transcription.TranscriptionService.CreateSession:input_type -> transcription.CreateSessionRequest
	2,  // 4: transcription.TranscriptionService.StreamAudio:input_type -> transcription.AudioChunk
	4,  // 5: transcription.TranscriptionService.EndSession:input_type -> transcription.EndSessionRequest
	6,  // 6: transcription.TranscriptionService.GetSessionTranscriptions:input_type -> transcription.GetSessionTranscriptionsRequest
	9,  // 7: transcription.TranscriptionService.SearchTranscriptions:input_type -> transcription.SearchTranscriptionsRequest
	1,  // 8: transcription.TranscriptionService.CreateSession:output_type -> transcription.CreateSessionResponse
	3,  // 9: transcription.TranscriptionService.StreamAudio:output_type -> transcription.TranscriptionResult
	5,  // 10: transcription.TranscriptionService.EndSession:output_type -> transcription.EndSessionResponse
	7,  // 11: transcription.TranscriptionService.GetSessionTranscriptions:output_type -> transcription.GetSessionTranscriptionsResponse
	10, // 12: transcription.TranscriptionService.SearchTranscriptions:output_type -> transcription.SearchTranscriptionsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_transcription_proto_init() }
func file_api_proto_transcription_proto_init() {
	if File_api_proto_transcription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_transcription_proto_rawDesc), len(file_api_proto_transcription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_transcription_proto_goTypes,
		DependencyIndexes: file_api_proto_transcription_proto_depIdxs,
		MessageInfos:      file_api_proto_transcription_proto_msgTypes,
	}.Build()
	File_api_proto_transcription_proto = out.File
	file_api_proto_transcription_proto_goTypes = nil
	file_api_proto_transcription_proto_depIdxs = nil
}
